#include <iostream>
#include <windows.h>
#include <signal.h>
#include <tchar.h>
#include <vector>
#include <fstream>
#include <algorithm>
#include <iomanip>
#include <string>
#include <map>
#include <sstream>
#include <conio.h>
#include <ctime>

using std::map;
using std::ios;
using std::cout;
using std::cin;
using std::endl;
using std::fstream;
using std::vector;
using std::string;
using std::stringstream;
using std::find;